language: java
jdk:
  - oraclejdk7

services:
  - mongodb

before_script:
  - sleep 15
  - mongo mydb --eval "db.customers.insert([{firstName: 'John', lastName: 'Smith'}, {firstName: 'Joe', lastName: 'Smith'}, {firstName: 'Bob', lastName: 'Smith'}, {firstName: 'Ted', lastName: 'Smith'}]);"

